services:
  php-app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./2aEval:/var/www/html

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: examen
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
